name: Run lint and static analyis checks
on:
  workflow_call:
    inputs:
      actionlint-enable:
        description: Controls whether to run the actionlint job
        default: true
        required: false
        type: boolean
      tardigradelint-enable:
        description: Controls whether to run the tardigradelint job
        default: true
        required: false
        type: boolean
      tardigradelint-target:
        description: Name of the Tardigrade-CI Makefile target to run
        default: lint
        required: false
        type: string

jobs:
  tardigradelint:
    if: inputs.tardigradelint-enable
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone this git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Project Syntax Verification
        run: make docker/run target="${{ inputs.tardigradelint-target }}"

  actionlint:
    if: inputs.actionlint-enable
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Check workflow files
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283
