name: Create GitHub Release

on:
  # Run as a reusable workflow
  workflow_call:
    inputs:
      mockstacktest-enable:
        description: Controls whether to run the mockstacktest job
        default: true
        required: false
        type: boolean
      mockstacktest-pytest-args:
        description: Passes PYTEST_ARGS to mockstacktest
        default: -v
        required: false
        type: string
      tardigradelint-enable:
        description: Controls whether to run the tardigradelint job
        default: true
        required: false
        type: boolean
      tardigradelint-target:
        description: Name of the Tardigrade-CI Makefile target to run
        default: lint
        required: false
        type: string
    secrets:
      release-token:
        description: Token with permissions to create GitHub Releases
        required: true
    outputs:
      release-condition:
        description: Whether the release was created or not
        value: ${{ jobs.release.outputs.release-condition }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      tardigradelint-enable: ${{ inputs.tardigradelint-enable }}
      tardigradelint-target: ${{ inputs.tardigradelint-target }}

  test:
    uses: ./.github/workflows/test.yml
    with:
      mockstacktest-enable: ${{ inputs.mockstacktest-enable }}
      mockstacktest-pytest-args: ${{ inputs.mockstacktest-pytest-args }}

  release:
    needs:
      - lint
      - test
    # The test and lint workflows are optional, and may be "skipped". The release should be
    # created as long as the jobs do not fail. See also:
    #   <https://samanpavel.medium.com/github-actions-conditional-job-execution-e6aa363d2867>
    if: |
      always() &&
      (needs.lint.result == 'success' || needs.lint.result == 'skipped') &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    outputs:
      release-condition: ${{ steps.release.outputs.release-condition }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project for release
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Checkout release action
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          repository: plus3it/actions-workflows
          path: .github/temp/actions-workflows
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/actions/release/action.yml
      - name: Move release action
        run: |
          mkdir -p .github/actions/release
          mv .github/temp/actions-workflows/.github/actions/release/action.yml .github/actions/release/action.yml
      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          release-token: ${{ secrets.release-token }}
